# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9ceec631fdc74bed38bb5b4a9ce3656346c65d4933640eeea59d6dc11f767e6ae33bf78f30c75665f26a330f069409dc656b67864dadd3033b6f8e0d8c6a21f

test:
  secret_key_base: 96cfdbe24467545f92dd90ad9113ad00dd9c69f915f5a9df0c7ab15d87ce0c4428c7b26fb3a89b7754df1a7609ad0becf25406c72ad593eb6afdd23ca4cdd871

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
